[project]
name = "photobooth-array"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "fastapi==0.117.1",
    "python-multipart>=0.0.20",
    "schedule>=1.2.2",
    "uvicorn[standard]>=0.37.0",
]
